version: ‘3.9’

services:
  mariadb:
    image: mariadb:10.11.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345

  adminer:
    image: phpmyadmin:5.2.1
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1


